package br.com.farabolini.challenge.domain.interceptors.transfer;

public interface TransferInterceptorOrder {

    int SENDER_ACCOUNT_INTERCEPTOR_ORDER = 1;
    int RECIPIENT_ACCOUNT_INTERCEPTOR_ORDER = SENDER_ACCOUNT_INTERCEPTOR_ORDER + 1;
    int SUFFICIENT_BALANCE_INTERCEPTOR_ORDER = RECIPIENT_ACCOUNT_INTERCEPTOR_ORDER + 1;
    int SENDER_DAILY_LIMIT_NOT_EXCEEDED_INTERCEPTOR_ORDER = SUFFICIENT_BALANCE_INTERCEPTOR_ORDER + 1;

}
